# Generated by Django 5.0.7 on 2024-07-28 11:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('puppy', 'Puppy'), ('kitten', 'Kitten')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stray_photos/')),
                ('is_adopted', models.BooleanField(default=False)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
