# Generated by Django 5.0.7 on 2024-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stray',
            old_name='date_reported',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stray',
            old_name='species',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='stray',
            name='age',
        ),
        migrations.RemoveField(
            model_name='stray',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='stray',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stray',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stray',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
